import { Employee } from "../../../models/employee";

export const EMPLOYEES:Employee[]=[
    {
        empCode:'emp01',
        Name:'X',
        Experience:5,
        SalaryPerMonth:50000,
        Technology:'JAVA',
        seatingCost:20000,
        hasProject: true
    },
    {
        empCode:'emp02',
        Name:'Y',
        Experience:5,
        SalaryPerMonth:50000,
        Technology:'JAVA,Angular',
        seatingCost:20000,
        hasProject: false
    },
    {
        empCode:'emp03',
        Name:'Z',
        Experience:5,
        SalaryPerMonth:50000,
        Technology:'ReactJS',
        seatingCost:20000,
        hasProject:true
    },
    {
        empCode:'emp04',
        Name:'XY',
        Experience:5,
        SalaryPerMonth:50000,
        Technology:'JAVA',
        seatingCost:20000,
        hasProject: true
    },
    {
        empCode:'emp05',
        Name:'YD',
        Experience:5,
        SalaryPerMonth:50000,
        Technology:'JAVA,Angular',
        seatingCost:20000,
        hasProject: false
    },
    {
        empCode:'emp06',
        Name:'ZT',
        Experience:5,
        SalaryPerMonth:50000,
        Technology:'ReactJS',
        seatingCost:20000,
        hasProject:true,
    },
    {
        empCode:'emp04',
        Name:'A',
        Experience:5,
        SalaryPerMonth:60000,
        Technology:'ReactJS',
        seatingCost:20000,
        hasProject:true,
    },
    {
        empCode:'emp05',
        Name:'B',
        Experience:5,
        SalaryPerMonth:40000,
        Technology:'ReactJS',
        seatingCost:20000,
        hasProject:true,
    },
    {
        empCode:'emp06',
        Name:'C',
        Experience:5,
        SalaryPerMonth:35000,
        Technology:'ReactJS',
        seatingCost:20000,
        hasProject:true,
    }
]